node_templates:
  jboss:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create: scripts/jboss/create.sh
        configure: scripts/jboss/configure.sh
        start: scripts/jboss/start.sh
        stop: scripts/jboss/stop.sh
    relationships:
      - type: cloudify.relationships.contained_in
        target: vm

#  app:
#    type: cloudify.terminal.raw
#    interfaces:
#      cloudify.interfaces.lifecycle:
#        start:
#          inputs:
#            terminal_auth: *terminal_auth
#            calls:
#              - template: components/jboss-app/start.sh
#                params:
#                  app_url: { get_input: app_url }
#                  app_name: { get_input: app_name }
#        stop:
#          inputs:
#            terminal_auth: *terminal_auth
#            calls:
#              - template: components/jboss-app/stop.sh
#                params:
#                  app_name: { get_input: app_name }
#    relationships:
#      - type: cloudify.relationships.depends_on
#        target: jboss